/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  summary?: string;
  slug?: Slug;
  author?: AuthorReference;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  theme?: "technology" | "career" | "learning" | "mythology" | "hobbies";
  tags?: Array<string>;
  publishedAt?: string;
  body?: BlockContent;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
  | {
      url?: string;
      _type: "youtube";
      _key: string;
    }
>;

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  shortBio?: string;
  focusTags?: Array<string>;
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  parent?: CategoryReference;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | AuthorReference
  | SanityImageAssetReference
  | CategoryReference
  | Post
  | BlockContent
  | SanityImageCrop
  | SanityImageHotspot
  | Author
  | Slug
  | Category
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

type ArrayOf<T> = Array<
  T & {
    _key: string;
  }
>;

// Source: app/(blog)/kategori/[...slug]/page.tsx
// Variable: categoryPostsQuery
// Query: *[_type == "post" && references($categoryIds)] | order(publishedAt desc) {    _id,    title,    slug,    publishedAt,    excerpt,    "plainBody": pt::text(body),    "mainImage": mainImage.asset->url,    "authorName": author->name  }
export type CategoryPostsQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  publishedAt: string | null;
  excerpt: null;
  plainBody: string;
  mainImage: string | null;
  authorName: string | null;
}>;

// Source: app/(blog)/page.tsx
// Variable: postsQuery
// Query: *[_type == "post"] | order(publishedAt desc) {    _id,    title,    slug,    publishedAt,    excerpt,    "mainImage": mainImage.asset->url,    "authorName": author->name  }
export type PostsQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  publishedAt: string | null;
  excerpt: null;
  mainImage: string | null;
  authorName: string | null;
}>;

// Source: app/(blog)/posts/[slug]/page.tsx
// Variable: singlePostQuery
// Query: *[_type == "post" && slug.current == $slug][0] {    title,    body,    publishedAt,    excerpt,    "mainImage": mainImage.asset->url,    "authorName": author->name  }
export type SinglePostQueryResult = {
  title: string | null;
  body: BlockContent | null;
  publishedAt: string | null;
  excerpt: null;
  mainImage: string | null;
  authorName: string | null;
} | null;

// Source: app/(blog)/yazar/[slug]/page.tsx
// Variable: authorPageQuery
// Query: {    "author": *[_type == "author" && slug.current == $slug][0] {      name,      "image": image.asset->url,      "bioText": pt::text(bio)    },    "posts": *[_type == "post" && author->slug.current == $slug] | order(publishedAt desc) {      _id,      title,      slug,      publishedAt,      excerpt,      "plainBody": pt::text(body),      "mainImage": mainImage.asset->url,      "categories": categories[]->{"title": title, "slug": slug.current}    }  }
export type AuthorPageQueryResult = {
  author: {
    name: string | null;
    image: string | null;
    bioText: string;
  } | null;
  posts: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
    publishedAt: string | null;
    excerpt: null;
    plainBody: string;
    mainImage: string | null;
    categories: Array<{
      title: string | null;
      slug: string | null;
    }> | null;
  }>;
};

// Source: sanity/lib/queries.ts
// Variable: settingsQuery
// Query: *[_type == "settings"][0]
export type SettingsQueryResult = null;

// Source: sanity/lib/queries.ts
// Variable: heroQuery
// Query: *[_type == "post" && defined(slug.current)] | order(date desc, _updatedAt desc) [0] {    "content": body,      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  "excerpt": coalesce(excerpt, pt::text(body)[0..160]),  "coverImage": mainImage,  "date": coalesce(publishedAt, _updatedAt),  "author": author->{"name": coalesce(name, "Anonymous"), "picture": image},  }
export type HeroQueryResult = {
  content: BlockContent | null;
  _id: string;
  status: "draft" | "published";
  title: string | "Untitled";
  slug: string | null;
  excerpt: null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  date: string;
  author: {
    name: string | "Anonymous";
    picture: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: moreStoriesQuery
// Query: *[_type == "post" && _id != $skip && defined(slug.current)] | order(date desc, _updatedAt desc) [0...$limit] {      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  "excerpt": coalesce(excerpt, pt::text(body)[0..160]),  "coverImage": mainImage,  "date": coalesce(publishedAt, _updatedAt),  "author": author->{"name": coalesce(name, "Anonymous"), "picture": image},  }
export type MoreStoriesQueryResult = Array<{
  _id: string;
  status: "draft" | "published";
  title: string | "Untitled";
  slug: string | null;
  excerpt: null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  date: string;
  author: {
    name: string | "Anonymous";
    picture: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: postQuery
// Query: *[_type == "post" && slug.current == $slug] [0] {    "content": body,      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  "excerpt": coalesce(excerpt, pt::text(body)[0..160]),  "coverImage": mainImage,  "date": coalesce(publishedAt, _updatedAt),  "author": author->{"name": coalesce(name, "Anonymous"), "picture": image},  }
export type PostQueryResult = {
  content: BlockContent | null;
  _id: string;
  status: "draft" | "published";
  title: string | "Untitled";
  slug: string | null;
  excerpt: null;
  coverImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  date: string;
  author: {
    name: string | "Anonymous";
    picture: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: categoryTreeQuery
// Query: *[_type == "category" && !defined(parent)] {    _id,    title,    slug,    "children": *[_type == "category" && parent._ref == ^._id] {      _id,      title,      slug,      "children": *[_type == "category" && parent._ref == ^._id] {        _id,        title,        slug      }    }  }
export type CategoryTreeQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  children: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
    children: Array<{
      _id: string;
      title: string | null;
      slug: Slug | null;
    }>;
  }>;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "post" && references($categoryIds)] | order(publishedAt desc) {\n    _id,\n    title,\n    slug,\n    publishedAt,\n    excerpt,\n    "plainBody": pt::text(body),\n    "mainImage": mainImage.asset->url,\n    "authorName": author->name\n  }\n': CategoryPostsQueryResult;
    '\n  *[_type == "post"] | order(publishedAt desc) {\n    _id,\n    title,\n    slug,\n    publishedAt,\n    excerpt,\n    "mainImage": mainImage.asset->url,\n    "authorName": author->name\n  }\n': PostsQueryResult;
    '\n  *[_type == "post" && slug.current == $slug][0] {\n    title,\n    body,\n    publishedAt,\n    excerpt,\n    "mainImage": mainImage.asset->url,\n    "authorName": author->name\n  }\n': SinglePostQueryResult;
    '\n  {\n    "author": *[_type == "author" && slug.current == $slug][0] {\n      name,\n      "image": image.asset->url,\n      "bioText": pt::text(bio)\n    },\n    "posts": *[_type == "post" && author->slug.current == $slug] | order(publishedAt desc) {\n      _id,\n      title,\n      slug,\n      publishedAt,\n      excerpt,\n      "plainBody": pt::text(body),\n      "mainImage": mainImage.asset->url,\n      "categories": categories[]->{"title": title, "slug": slug.current}\n    }\n  }\n': AuthorPageQueryResult;
    '*[_type == "settings"][0]': SettingsQueryResult;
    '\n  *[_type == "post" && defined(slug.current)] | order(date desc, _updatedAt desc) [0] {\n    "content": body,\n    \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  "excerpt": coalesce(excerpt, pt::text(body)[0..160]),\n  "coverImage": mainImage,\n  "date": coalesce(publishedAt, _updatedAt),\n  "author": author->{"name": coalesce(name, "Anonymous"), "picture": image},\n\n  }\n': HeroQueryResult;
    '\n  *[_type == "post" && _id != $skip && defined(slug.current)] | order(date desc, _updatedAt desc) [0...$limit] {\n    \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  "excerpt": coalesce(excerpt, pt::text(body)[0..160]),\n  "coverImage": mainImage,\n  "date": coalesce(publishedAt, _updatedAt),\n  "author": author->{"name": coalesce(name, "Anonymous"), "picture": image},\n\n  }\n': MoreStoriesQueryResult;
    '\n  *[_type == "post" && slug.current == $slug] [0] {\n    "content": body,\n    \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  "excerpt": coalesce(excerpt, pt::text(body)[0..160]),\n  "coverImage": mainImage,\n  "date": coalesce(publishedAt, _updatedAt),\n  "author": author->{"name": coalesce(name, "Anonymous"), "picture": image},\n\n  }\n': PostQueryResult;
    '\n  *[_type == "category" && !defined(parent)] {\n    _id,\n    title,\n    slug,\n    "children": *[_type == "category" && parent._ref == ^._id] {\n      _id,\n      title,\n      slug,\n      "children": *[_type == "category" && parent._ref == ^._id] {\n        _id,\n        title,\n        slug\n      }\n    }\n  }\n': CategoryTreeQueryResult;
  }
}
